version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: app/scripts/install.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: app/scripts/cleanup.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: app/scripts/start.sh
      timeout: 60
      runas: ec2-user
