version: 0.2


phases:
  install:
    commands:
      - echo "Iniciando buildspec para appspec dinámico..."

  build:
    commands:
      - echo "Copiando appspec-$DEPLOY_TYPE.yml..."
      - cp app/deploy-ec2/appspec-ec2.yml appspec.yml

artifacts:
  files:
    - appspec.yml
    - app/deploy-ec2/scripts/**/*
    - app/**/*
