version: 0.2

phases:

  build:
    commands:
      - echo "Copiando appspec-ec2.yml como appspec.yml..."
      - cp app/deploy-ec2/appspec-ec2.yml appspec.yml
      - echo "Contenido de appspec.yml:"
      - cat appspec.yml
      - echo "Archivos presentes:"
      - find .

artifacts:
  files:
    - appspec.yml
    - app/deploy-ec2/scripts/**/*
