version: 0.2


phases:

  build:
    commands:
      - echo "Copiando appspec-ec2.yml..."
      - mkdir -p build-output
      - cp app/deploy-ec2/appspec-ec2.yml build-output/appspec.yml
      - cp -r app/deploy-ec2/scripts build-output/

artifacts:
  base-directory: build-output
  files:
    - appspec.yml
    - scripts/**/*
